Improvements for the "MultisendUpgradeable" contract
cloudwalk/smart-rewards pull request #9
Opened 2022-01-24 14:49 UTC by EvgeniiZaitsevCW

Several improvements of the "MultisendUpgradeable" contract and the appropriate changes in the tests

2022-01-25 13:55 UTC, IgorSenychCW requested changes

2022-01-25 13:55 UTC, IgorSenychCW commented on contracts/upgradeable/MultisendUpgradeable.sol
This empty line (59) could be removed.

2022-01-25 14:14 UTC, EvgeniiZaitsevCW commented on contracts/upgradeable/MultisendUpgradeable.sol
I agree.
The empty line has been removed.
If you have other suggestions, please share.

2022-01-26 09:54 UTC, IgorSenychCW approved these changes

2022-01-26 15:40 UTC, arthur-cw approved these changes
:+1:

2022-01-26 15:57 UTC, merged